export const ROLE_SCOPE_PLATEVERIFY = 'ROLE_SCOPE_PLATEVERIFY';
export const ROLE_SCOPE_SCHOOL = 'ROLE_SCOPE_SCHOOL';
export const ROLE_MANAGE_ALL = 'ROLE_MANAGE_ALL';
export const ROLE_MANAGE_ALERT = 'ROLE_MANAGE_ALERT';
export const ROLE_MANAGE_MEMBER = 'ROLE_MANAGE_MEMBER';
export const ROLE_MANAGE_VEHICLE = 'ROLE_MANAGE_VEHICLE';
